version: 2

models:
  - name: fact_trip
    description: "Fact Trip"
    columns:
      - name: vendor_key
        data_tests:
          - not_null
      - name: rate_code_key
        data_tests:
          - not_null
      - name: pickup_location_id
        data_tests:
          - not_null
      - name: dropoff_location_id
        data_tests:
          - not_null
      - name: payment_type_key
        data_tests:
          - not_null
      - name: service_type_id
        data_tests:
          - not_null
      - name: passenger_count
        data_tests:
          - not_null
      - name: trip_distance
        data_tests:
          - not_null
      - name: total_amount
        data_tests:
          - not_null

  - name: dim_dropoff_location
    columns:
      - name: dropoff_location_id
        data_tests:
          - unique
          - not_null
      - name: dropoff_latitude
        data_tests:
          - not_null
      - name: dropoff_longitude
        data_tests:
          - not_null

  - name: dim_pickup_location
    columns:
      - name: pickup_location_id
        data_tests:
          - unique
          - not_null
      - name: pickup_latitude
        data_tests:
          - not_null
      - name: pickup_longitude
        data_tests:
          - not_null

  - name: dim_payment
    columns:
      - name: payment_description
        data_tests:
          - not_null

  - name: dim_rate_code
    columns:
      - name: rate_code_description
        data_tests:
          - not_null

  - name: dim_service
    columns:
      - name: service_name
        data_tests:
          - not_null

  - name: dim_vendor
    columns:
      - name: vendor_name
        data_tests:
          - not_null