nyc_data:
  folder_path: data
datalek:
  endpoint: localhost:9000
  bucket_name_1: raw
  bucket_name_2: processed
  bucket_name_3: sandbox
  folder_name: batch
  acess_key: minio_acess_key
  secret_key: minio_secret_key
  

